### ISSUE TITLE
hi markus-oberlehner is posible hide the links

### ISSUE THREAD

**Issue by abdiasriver** [maoberlehner/markus-oberlehner-net#74]
markus-oberlehner i was tested your theme and i very happy to learn more about this great theme.

I'm starting in the world of hugo and your topic has seemed very interesting
I'm a little confused about the menu, if I make a folder in content, a link is created, I would like to know how to hide it or ignore it, just show what is done in the config.toml
 
[Blog](https://termcode.github.io/)
you can see the menu, I want to delete it from the menu (blog, otros, utilidades), just leave the links of the .toml

this is the code of your partial menu

```
{{ if ne .Site.Params.show_menu false }}
  <nav class="c-main-nav" itemscope itemtype="http://schema.org/SiteNavigationElement">
    {{ $currentNode := . }}
    {{ range  $i, $v := .Site.Menus.main }}
      <a class="c-main-nav__link {{if or ($currentNode.IsMenuCurrent "main" .) ($currentNode.HasMenuCurrent "main" .) }}is-active{{end}}" href="{{ .URL }}">
        <span itemprop="name">{{ .Name }}</span>
      </a>
      {{ if not $i }}<span class="c-main-nav__divide"> | </span>{{ end }}
    {{ end }}
  </nav>
{{ end }}
```

thanks ....markus youre big

**Comment by maoberlehner** [comment]
Hey @abdiasriver,

Thank you for your kind words. I'm currently busy, but I'll try to look into your problem during the following days.
I'm happy my theme is useful to you.

**Comment by maoberlehner** [comment]
Hello @abdiasriver, I've finally figured it out.

The reason why the menu item is created automatically is the following setting in the `config.toml`

```
SectionPagesMenu = "main"
```

If you remove this setting, you have to manually add every page to the menu. You can do this either in the `config.toml` or by adding `menu = "main"` to the configuration block of the `_index.md` file.
